
package autonoma.Biblioteca.view;

import autonoma.Biblioteca.models.Biblioteca;
import autonoma.Biblioteca.models.Libro;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;



public class PaginaP extends javax.swing.JFrame {
       private Biblioteca biblioteca;
       private JPanel OrdenAlfabetico;
   

    
    public PaginaP() {
        biblioteca = new Biblioteca();
        initComponents();
                
                this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/BibliotecaPOO/images/Biblioteca.png")).getImage());
        }catch(Exception e){
            
        }
        llenarTablaLibros();
        
    }

        public Biblioteca getBiblioteca(){
        return biblioteca;
        }
        public JTable getTablaLibros(){
            return TablaLibros;
        }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        AgregarLibro = new javax.swing.JPanel();
        Agregar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BuscarLibro = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        ActualizarLibro = new javax.swing.JPanel();
        Actualizar = new javax.swing.JLabel();
        EliminarLibro = new javax.swing.JPanel();
        Eliminar = new javax.swing.JLabel();
        OrdenarAlfabeticamente = new javax.swing.JPanel();
        Ordenar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaLibros = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(214, 219, 223));

        jLabel6.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        jLabel6.setText("Biblioteca");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel6)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(133, 146, 158));

        AgregarLibro.setBackground(new java.awt.Color(133, 146, 158));
        AgregarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AgregarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AgregarLibroMouseExited(evt);
            }
        });

        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Biblioteca/images/AgregarLibro.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel7.setText("Agregar Libro");

        javax.swing.GroupLayout AgregarLibroLayout = new javax.swing.GroupLayout(AgregarLibro);
        AgregarLibro.setLayout(AgregarLibroLayout);
        AgregarLibroLayout.setHorizontalGroup(
            AgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLibroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Agregar)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarLibroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AgregarLibroLayout.setVerticalGroup(
            AgregarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLibroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        BuscarLibro.setBackground(new java.awt.Color(133, 146, 158));
        BuscarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarLibroMouseExited(evt);
            }
        });

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Biblioteca/images/BuscarLibro.png"))); // NOI18N

        javax.swing.GroupLayout BuscarLibroLayout = new javax.swing.GroupLayout(BuscarLibro);
        BuscarLibro.setLayout(BuscarLibroLayout);
        BuscarLibroLayout.setHorizontalGroup(
            BuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLibroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Buscar)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        BuscarLibroLayout.setVerticalGroup(
            BuscarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarLibroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Buscar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        ActualizarLibro.setBackground(new java.awt.Color(133, 146, 158));
        ActualizarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualizarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualizarLibroMouseExited(evt);
            }
        });

        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Biblioteca/images/Actualizar.png"))); // NOI18N

        javax.swing.GroupLayout ActualizarLibroLayout = new javax.swing.GroupLayout(ActualizarLibro);
        ActualizarLibro.setLayout(ActualizarLibroLayout);
        ActualizarLibroLayout.setHorizontalGroup(
            ActualizarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarLibroLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(Actualizar)
                .addGap(10, 10, 10))
        );
        ActualizarLibroLayout.setVerticalGroup(
            ActualizarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarLibroLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(Actualizar)
                .addGap(10, 10, 10))
        );

        EliminarLibro.setBackground(new java.awt.Color(133, 146, 158));
        EliminarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarLibroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EliminarLibroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarLibroMouseExited(evt);
            }
        });

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Biblioteca/images/EliminarLibro.png"))); // NOI18N

        javax.swing.GroupLayout EliminarLibroLayout = new javax.swing.GroupLayout(EliminarLibro);
        EliminarLibro.setLayout(EliminarLibroLayout);
        EliminarLibroLayout.setHorizontalGroup(
            EliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarLibroLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(Eliminar)
                .addGap(10, 10, 10))
        );
        EliminarLibroLayout.setVerticalGroup(
            EliminarLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLibroLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Eliminar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        OrdenarAlfabeticamente.setBackground(new java.awt.Color(133, 146, 158));
        OrdenarAlfabeticamente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdenarAlfabeticamenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OrdenarAlfabeticamenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrdenarAlfabeticamenteMouseExited(evt);
            }
        });

        Ordenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/Biblioteca/images/OrdenarLibros.png"))); // NOI18N

        javax.swing.GroupLayout OrdenarAlfabeticamenteLayout = new javax.swing.GroupLayout(OrdenarAlfabeticamente);
        OrdenarAlfabeticamente.setLayout(OrdenarAlfabeticamenteLayout);
        OrdenarAlfabeticamenteLayout.setHorizontalGroup(
            OrdenarAlfabeticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenarAlfabeticamenteLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(Ordenar)
                .addGap(10, 10, 10))
        );
        OrdenarAlfabeticamenteLayout.setVerticalGroup(
            OrdenarAlfabeticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrdenarAlfabeticamenteLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(Ordenar)
                .addGap(10, 10, 10))
        );

        jLabel11.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel11.setText("Buscar Libro");

        jLabel12.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel12.setText("Actualizar Libro");

        jLabel13.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel13.setText("Eliminar Libro");

        jLabel14.setFont(new java.awt.Font("Dubai Medium", 1, 12)); // NOI18N
        jLabel14.setText("Ordenar Libros");

        TablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Titulo"
            }
        ));
        jScrollPane1.setViewportView(TablaLibros);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActualizarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(EliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(OrdenarAlfabeticamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrdenarAlfabeticamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActualizarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(BuscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)))
                        .addComponent(AgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLibroMouseEntered
       this.mouseEntered(AgregarLibro);
    }//GEN-LAST:event_AgregarLibroMouseEntered

    private void AgregarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLibroMouseExited
         this.mouseExited(AgregarLibro);
    }//GEN-LAST:event_AgregarLibroMouseExited

    private void AgregarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarLibroMouseClicked
        agregarLibro agregar = new agregarLibro(this, true, biblioteca, this);
        agregar.setVisible(true);
    }//GEN-LAST:event_AgregarLibroMouseClicked

    private void BuscarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLibroMouseEntered
         this.mouseEntered(BuscarLibro);
    }//GEN-LAST:event_BuscarLibroMouseEntered

    private void BuscarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLibroMouseClicked
        BuscarLibro ventanaBuscar = new BuscarLibro(this.biblioteca, this);
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_BuscarLibroMouseClicked

    private void BuscarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarLibroMouseExited
         this.mouseExited(BuscarLibro);

    }//GEN-LAST:event_BuscarLibroMouseExited

    private void ActualizarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLibroMouseEntered
        this.mouseEntered(ActualizarLibro);
    }//GEN-LAST:event_ActualizarLibroMouseEntered

    private void ActualizarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLibroMouseClicked
        actualizarLibro Actualizar = new actualizarLibro(this);
        Actualizar.setVisible(true);
            
    }//GEN-LAST:event_ActualizarLibroMouseClicked

    private void ActualizarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarLibroMouseExited
       this.mouseEntered(ActualizarLibro);
    }//GEN-LAST:event_ActualizarLibroMouseExited

    private void EliminarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLibroMouseClicked
       new eliminarLibro(this, true, biblioteca, this).setVisible(true);
    }//GEN-LAST:event_EliminarLibroMouseClicked

    private void EliminarLibroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLibroMouseEntered
        this.mouseEntered(EliminarLibro);
    }//GEN-LAST:event_EliminarLibroMouseEntered

    private void EliminarLibroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLibroMouseExited
       this.mouseEntered(EliminarLibro);
    }//GEN-LAST:event_EliminarLibroMouseExited

    private void OrdenarAlfabeticamenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenarAlfabeticamenteMouseClicked
        new OrdenAlfabetico(this, true).setVisible(true);
    }//GEN-LAST:event_OrdenarAlfabeticamenteMouseClicked

    private void OrdenarAlfabeticamenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenarAlfabeticamenteMouseEntered
         this.mouseEntered(OrdenAlfabetico);
    }//GEN-LAST:event_OrdenarAlfabeticamenteMouseEntered

    private void OrdenarAlfabeticamenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdenarAlfabeticamenteMouseExited
         this.mouseEntered(OrdenAlfabetico);
    }//GEN-LAST:event_OrdenarAlfabeticamenteMouseExited

        private void mouseEntered(JPanel panel){
        panel.setBackground(new Color(79,149,157));
        
    }
    private void mouseExited(JPanel panel){
        panel.setBackground(new Color(87,180,186));
    }
   
public void llenarTablaLibros() {
    DefaultTableModel modelo = (DefaultTableModel) TablaLibros.getModel();
    modelo.setRowCount(0); // Limpiar la tabla antes de llenarla

    for (Libro libro : biblioteca.getLibros()) { // ← Asegúrate de que esta función existe en Biblioteca
        modelo.addRow(new Object[]{libro.getId(), libro.getTitulo()});
}
}

public void agregarLibroTabla(Libro libro) {
    DefaultTableModel modelo = (DefaultTableModel) TablaLibros.getModel();
    modelo.addRow(new Object[]{libro.getId(), libro.getTitulo()});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actualizar;
    private javax.swing.JPanel ActualizarLibro;
    private javax.swing.JLabel Agregar;
    private javax.swing.JPanel AgregarLibro;
    private javax.swing.JLabel Buscar;
    private javax.swing.JPanel BuscarLibro;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JPanel EliminarLibro;
    private javax.swing.JLabel Ordenar;
    private javax.swing.JPanel OrdenarAlfabeticamente;
    private javax.swing.JTable TablaLibros;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}